### ISSUE TITLE
Sintesis de Calidad

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-IsraelNicolas61#1]
[Sintesis_Calidad_IsraelNicolásPérez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-IsraelNicolas61/files/9569317/Sintesis_Calidad_IsraelNicolasPerez.pdf)

**Comment by carlos-chrs** [comment]
Revisado 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
